const List<String> deathSentences = [
  "Oh no!",
  "You died!",
  "You have died!",
  "Oops, gravity strikes again!",
  "It's all fun and games, right?",
  "That was a creative way to fail!",
  "Well, that wasn't in the manual.",
  "Time to rethink your strategy!",
  "Try not to make that a habit.",
  "At least you're entertaining us!",
  "Really? You call that playing?",
  "Even my pet rock could do better.",
  "Just stop. Seriously.",
  "You're a disappointment.",
  "Did you even try?",
  "The bar is set low, and you missed.",
  "You're the weakest link, goodbye.",
  "Why bother anymore?",
  "You're not cut out for this.",
  "Quit while you're behind.",
  "It's pointless to continue.",
  "This isn't your game.",
  "Give up already.",
  "You'll never make it.",
  "Yea... those sentences are AI generated.",
  "Did your cat take the controller?",
  "Clearly, you're trying new tactics.",
  "Someone call for a lifeguard?",
  "That's one way to break the ice.",
  "A round of applause, or not.",
  "Is this a comedy or a tragedy?",
  "Well, that was a cinematic exit!",
  "Don't worry; it's just a flesh wound.",
  "You're a magnet for hilarity!",
  "You've discovered a new glitch!",
  "Are you playing in 'easy' mode?",
  "At least you make it entertaining.",
  "Gravity: 1, You: 0.",
  "Game over, but the memes live on.",
  "You're a legend in the fail department.",
  "The game feels sorry for you.",
  "That's a special kind of talent.",
  "Your mistakes are a work of art.",
  "Looks like chaos is your strategy.",
  "You must be an undercover comedian.",
  "The universe conspires against you.",
  "This is comedy gold, right?",
  "You're a hero in your own way.",
  "Your gameplay is out of this world.",
  "You've mastered the art of surprise.",
  "That's a plot twist for sure!",
  "You're a natural at the unexpected.",
  "It's not a bug; it's a feature!",
  "Your gaming style is avant-garde",
  "You're the Picasso of gaming",
  "Were you aiming for the obstacle?",
  "That's a new high score, right?",
  "You redefine 'unique' gameplay",
  "Round of applause for effort",
  "I see potential in your chaos",
  "This is like a comedy show",
  "Your mistakes are iconic",
  "You're a gaming trendsetter",
  "Is this a game or satire?",
  "You're writing a gaming history",
  "You make games more interesting",
  "You've unlocked a secret: failure",
  "The game wants to be you",
  "You're a gaming unicorn",
  "Can we get your autograph?",
  "The game loves your creativity",
  "You're the game's favorite comedian",
  "You're a one-person blooper reel",
  "It's like watching a comedy",
  "You're a legend in funny fails",
  "Every day's April Fools' Day",
  "Your gaming style: avant-garde",
  "The game enjoys your antics",
  "You're a walking game glitch",
  "Even the NPCs are laughing",
  "Your fails deserve a trophy",
  "You're the clown of gaming",
  "It's like a stand-up routine",
  "Gaming: You're doing it wrong",
  "You're the game's favorite punchline.",
  "You're a master of unintended comedy.",
  "This is a spectacular disaster.",
  "You're like a superhero without powers.",
  "Is this your first time playing?",
  "The game is crying tears of laughter.",
  "You're gaming's best-kept secret.",
  "Epic fails, brought to you by you.",
  "Your gameplay defies explanation.",
  "You're a professional at failing.",
  "It's a unique form of entertainment.",
  "You give 'game over' a new meaning.",
  "This is a tragicomedy masterpiece.",
  "Failure, thy name is gamer.",
  "Your skills are a rare spectacle.",
  "It's a comedy of errors, really.",
  "Every move is a punchline.",
  "Your fails are a work of art.",
  "You're a walking blooper reel.",
  "You make gaming interesting, at least.",
  "It's like a comedy festival in here.",
  "You're rewriting the gaming rulebook.",
  "Epic fails: starring you.",
  "You're the master of game quirks.",
  "Laugh or cry? It's hard to tell.",
  "Your fails are the best part of this game.",
  "It's like a stand-up routine.",
];
